# Generated by Django 3.0.7 on 2020-06-11 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail', models.ImageField(upload_to='static/blog/images')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=20)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
